name: Flyway Migration

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flyway Migration
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/sql:/flyway/sql \
            flyway/flyway:latest \
            -url=${{ secrets.DB_URL }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -connectRetries=10 \
            -baselineOnMigrate=true \
            migrate
