name: Flyway Migration

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flyway Migration
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/sql:/flyway/sql \
            flyway/flyway:latest \
            -url="jdbc:postgresql://ep-cold-sun-amjgpd78.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require" \
            -user="${{ secrets.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            -schemas=public \
            -connectRetries=10 \
            migrate
